# Generated by Django 5.2.3 on 2025-07-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='menmbership',
            new_name='membership',
        ),
    ]
